config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :comments
    member do
      post :notify_friend
    end
  end
  resources :users do
    member do 
      post :sign_up_mail
    end
  end
  resources :tournaments do
    resources :matches
  end
  
  
 namespace :api do
  resources :games
 end

  
  resource :session
  match "/login" => "sessions#new", :as => "login", via: [:get, :post]
  match "/logout" => "sessions#destroy", :as => "logout", via: [:get, :post]
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

  root 'games#index'

  
  match "tournament/:id/register" => "tournaments#register", as: :tournament_register, via: [:get, :post]
  
  match "my_matches" => "matches#list", as: :my_matches, via: [:get, :post]
  match "all_match" => "matches#all", as: :all_match, via: [:get, :post] 
  match "ranking" => "tournaments#ranking", as: :ranking, via: [:get, :post] 
  

end

app/views/notifier/email_friend.html.erb
<html>
<body>
<p>
One of your friends, <%= @sender_name %>,
thinks you like an article we have written.
</p>
 
<p>
Come check all the information about <strong><%= @game.title %></strong> at
<%= game_url @game, :host => 'localhost:3000' %>
</p>
</body>
</html>

app/views/notifier/email_friend.text.erb
Your friend <%= @sender_name %> thinks you may like the following article:
 
<%= @game.title %> - <%= game_url(@game, :host => "localhost:3000") %>

app/views/notifier/sign_up_mail.html.erb
<html>
<body>
<p>
Welcome, to our website ! Your account has been created at <%= @user.created_at%>
</p>
</body>
</html>