config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :comments
    member do
      post :notify_friend
    end
  end
  resources :users do
    member do 
      post :sign_up_mail
    end
  end
  resources :tournaments do
    resources :matches
  end
  
  
 namespace :api do
  resources :games
 end

  
  resource :session
  match "/login" => "sessions#new", :as => "login", via: [:get, :post]
  match "/logout" => "sessions#destroy", :as => "logout", via: [:get, :post]
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

  root 'games#index'

  
  match "tournament/:id/register" => "tournaments#register", as: :tournament_register, via: [:get, :post]
  
  match "my_matches" => "matches#list", as: :my_matches, via: [:get, :post]
  match "all_match" => "matches#all", as: :all_match, via: [:get, :post] 
  match "ranking" => "tournaments#ranking", as: :ranking, via: [:get, :post] 
  

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  belongs_to :user
  has_many :matches
  has_many :tournament_players
  has_many :tournament_games
  has_many :users, through: :tournament_players
  has_many :games, through: :tournament_games
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  accepts_nested_attributes_for :games

  validates_presence_of :name, :address
  validates_date :start_at, :on_or_after => lambda { Date.current }
  validates_date :end_at, :on_or_after => lambda { :start_at }
  
  def can_subscribe?(tournament, user)
    tournament.users.count < tournament.max_player && !tournament.users.exists?(user) && tournament.user != user 
  end 
  
  def is_admin?(tournament, user)
    true if tournament.user == user
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy, :register]
  before_action :set_games #, only: [:show, :edit, :update, :new]
  load_and_authorize_resource skip_load_resource only: [:create] 
  def index
    @tournaments = Tournament.all
  end
  
  def show
  end
  
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to tournaments_path, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
   end
  end
  
  def ranking
    @tournaments = Tournament.all
  end

  def register
    if @tournament.can_subscribe?(@tournament, current_user)
       if @tournament.users.push(current_user)
          redirect_to tournament_path(@tournament), notice: 'Subscription done !'
       else
         redirect_to tournament_path(@tournament), alert: "Subscription failed !"
      end
    else 
      redirect_to tournament_path(@tournament), alert: "We've reach the number of participants max !"
    end
  end
  
  def new
    @tournament = Tournament.new()
  end
  
  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.user = current_user #should be current_user.tournaments.new(tournament_params)
    params[:tournament_game][:game_id].reject! { |game| game.empty? }
    @tournament.games.push(Game.find(params[:tournament_game][:game_id]))
    @tournament.users.push(current_user) 
    respond_to do |format| 
      if @tournament.games.any? && @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { redirect_to new_tournament_path, alert: "Unable to save, make sure you checked one or more games" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end
  
   private
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end
   
   def set_games
     @games = Game.all
   end
   
    def tournament_params
      params.require(:tournament).permit(:name, :start_at, :end_at, :address, :longitude, :latitude, :max_player,
        :games_attributes => [:id])
      
    end
  
end

app/views/tournaments/_form.html.erb
<%= bootstrap_form_for(@tournament, :html => {:class => "form-horizontal"}) do |f| %>
  <div class="field">
    <%= f.text_field :name %>
    <%= f.text_field :address %>
    

    <%= f.date_select :start_at %>
    <%= f.date_select :end_at %>
    
    <%= f.select :max_player, options_for_select((8..64).step(8)) %> <!-- should step by 8 16 32 64 --> 
    

    
	Game played : 
    <table class="table">
    <% if @games %>
	    <% if @tournament.new_record? %>
		    <%= collection_check_boxes(:tournament_game, :game_id, @games, :id, :title) do |b| %>
		  		<tr><td><%= b.label { b.check_box + b.text} %> </td></tr>
			<% end %>
		<% else %>
			<% @tournament.games.each do |game| %>
				<tr><td><%= game.title %></td></tr>
			<% end %>
		<% end %>
	<% end %>	
	</table>

  </div>	
  <div class="actions">
  	<% if @tournament.new_record? %>
  		<%= f.submit "Create", :class => "btn btn-default" %>
  	<% else%>
  	 	<%= f.submit "Update", :class => "btn btn-default" %>
  	<%end%>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<div class="row row-offcanvas row-offcanvas-right">
      <h1>Listing tournaments</h1>
      
      <% unless @tournaments.empty? %>
      <table class="table">
            <% @tournaments.each do |tournament| %>
            	<tr>
					<td>
						Name : <%= link_to tournament.name, tournament_path(tournament) %> <br/> 
						Address : <%= tournament.address %> <br/><br/>
						Start : <%= tournament.start_at.to_time.strftime('%e %B %Y') %> <br/>
						End  : <%= tournament.end_at.to_time.strftime('%e %B %Y') %> <br/><br/>
						<% if can? :edit, Tournament %> <%= link_to "Matches Panel", tournament_matches_path(tournament) %> <% end %>
					</td>
					<td><%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{tournament.latitude}%2C#{tournament.longitude}", :class => "google-map" %></td>
                </tr>  
            <% end %>
       </table>		              
        <br>
      <% else %>
      		No tournament found !
      <% end %>
    <p><%if can? :create, Tournament %> <%= link_to "Add tournament", new_tournament_path %> <% end %></p>
</div>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/ranking.html.erb
<h1>Ranking : </h1>
	<% unless @tournaments.empty? %>
		<% @tournaments.each do |tournament| %>
		    <h2><%= tournament.name%></h2>
		    	<table class="table">
		    		<tr>
		    			<th>Email </th>
		    			<th>Score </th>
		    		</tr>
		    		<% tournament.users.each do |user| %>
		    		<tr>
		    			<td><%= user.email %></td>
		    			<td><%= user.score(tournament) %></td>
		    		</tr>
		    		<% end %>
		    	</table>
		    
		<% end %>
	<% else %>
		There is currently no ranking available
	<% end %>
	
	

app/views/tournaments/show.html.erb
<h2> <%= @tournament.name %></h2>
<table class="table">
	<tr><td>Address : </td><td><%= @tournament.address %></td></tr>
	<tr><td>Start : </td><td><%= @tournament.start_at.to_time.strftime('%e %B %Y') %></td></tr>
	<tr><td>End : </td><td><%= @tournament.end_at.to_time.strftime('%e %B %Y') %></td></tr>
	<tr><td>
		<h3> Games </h3>
			<ul>
				<% @tournament.games.each do |game| %>
					<li><%= game.title %> </li>
				<% end %>
			</ul>
	</td></tr>
	<tr><td>
		<h3> Subscribed </h3>
			<ul>
				<% @tournament.users.each do |user| %>
					<li><%= user.email %></li>
				<% end %>
			</ul>
	</td></tr>
</table>
<% if can? :register, Tournament%>
	<% if @tournament.can_subscribe?(@tournament, current_user) %>
		<p><%= link_to "Register to the tournament", tournament_register_path %></p> 
	<% end %>	
<% end %>

<%= link_to 'Back', tournaments_path %>