config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :comments
    member do
      post :notify_friend
    end
  end
  resources :users do
    member do 
      post :sign_up_mail
    end
  end
  resources :tournaments do
    resources :matches
  end
  
  
 namespace :api do
  resources :games
 end

  
  resource :session
  match "/login" => "sessions#new", :as => "login", via: [:get, :post]
  match "/logout" => "sessions#destroy", :as => "logout", via: [:get, :post]
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

  root 'games#index'

  
  match "tournament/:id/register" => "tournaments#register", as: :tournament_register, via: [:get, :post]
  
  match "my_matches" => "matches#list", as: :my_matches, via: [:get, :post]
  match "all_match" => "matches#all", as: :all_match, via: [:get, :post] 
  match "ranking" => "tournaments#ranking", as: :ranking, via: [:get, :post] 
  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :matches
  validates_presence_of :title, :note
  validates_numericality_of :note, :greater_than_or_equal_to => 0, less_than_or_equal_to: 10
  has_many :comments, :dependent => :nullify
  belongs_to :user
  has_many :tournament_games
  has_many :tournaments, through: :tournament_games
  mount_uploader :image, ImageUploader
  
  def owned_by?(owner)
    return false unless owner.is_a? User
    owner == user
  end
  
  
  def as_json(options={})
    super(:only => [:id, :title, :note])
  end
end

app/controllers/api/games_controller.rb
class API::GamesController < ApplicationController
  before_action :authenticate
  TOKEN = "railsgames"

  def index
    @games = Game.all
    render json: @games, status: 200
  end

  def update
    game = Game.find(params[:id])
    game.title = params[:title]
    game.save!
    render json: game, status: 200
    # game.update(game_params)
    # render json: game, status: 200
   end

  def show
    game = Game.find(params[:id])
    render json: game, status: 200
  end


  private


    def authenticate
      authenticate_or_request_with_http_token do |token, options|
        token == TOKEN
      end
    end

    def game_params
      params.require(:game).permit(:title, :note, :image)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :notify_friend]
  load_and_authorize_resource skip_load_resource only: [:create]
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @comments = @game.comments

  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    # if @game.user.id == current_user.id
      respond_to do |format|
        if @game.update(game_params)
          format.html { redirect_to @game, notice: 'Game was successfully updated.' }
          format.json { render :show, status: :ok, location: @game }
        else
          format.html { render :edit }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    # else
    #   redirect_to root_path, :alert => "Not permitted"
    # end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    if @game.user.id == current_user.id
      @game.destroy
      respond_to do |format|
        format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, :alert => "Not permitted"
    end
  end
  
  def notify_friend
    Notifier.email_friend(@game, params[:name], params[:email]).deliver
    redirect_to @game, :notice => "Mail sended successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :note, :image)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= bootstrap_form_for(@game, :html =>{:multipart => true}) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>btn btn-default
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>

    <%= f.number_field :note, help: "Must be between 0 and 10" %>
    
    <%= f.file_field :image %>
  </div>	
  <div class="actions">
    <% if @game.new_record? %>
  		<%= f.submit "Create", :class => "btn btn-default" %>
  	<% else%>
  	 	<%= f.submit "Update", :class => "btn btn-default" %>
  	<%end%>
  </div>
<% end %>

app/views/games/_notify_friend.html.erb
<%= form_tag(notify_friend_game_path(@game), :id => 'notify_friend_form') do %>
<div class="field">
<%= label_tag :name, 'Your name' %><br />
<%= text_field_tag :name %>
</div>
<div class="field">
<%= label_tag :email, "Your friend's email" %><br />
<%= text_field_tag :email %>
</div>
<div class="actions">
<%= submit_tag 'Send' %> or
<%= link_to 'Cancel', '#', :onclick => "$('#notify_friend_form').slideUp()" %>
</div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="row row-offcanvas row-offcanvas-right">
      <h1>Listing games</h1>
      <table class="table">
            <% @games.each_with_index do |game, index| %>
            	<tr>
					  <td>
					  	<% if game.image? %>
					  		<%= link_to image_tag(game.image_url.to_s, :class => 'poster'), game_path(game.id)%>
					  	<% else %>
					  		No available image
					  	<% end %>	
					  </td> 
					  <td>
					  	<strong>Title :</strong><%= game.title %><br/>
	                    <strong>Note :</strong><%= game.note %><br/>
	                    <strong>Actions :</strong>
	                    	<%= link_to 'Show ', game %>
	                        <% if game.owned_by? current_user %>    
	                            <%= link_to 'Edit ', edit_game_path(game) %>
	                            <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %>
	                        <% end %>
                </tr>  
            <% end %>
       </table>		              
        <br>
    </div>
  <% if can? :create, Game %>  <%= link_to image_tag("new_game.png"), new_game_path %> <%end %>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<table class="table">
 <% if @game.image? %><tr><td> <%= image_tag @game.image_url.to_s %> </td></tr><% end %>
  <tr>
  	<td id="title"><strong>Title :</strong> <%= @game.title %></td>
  </tr>
  <tr>
  	<td><strong>Note :</strong> <%= @game.note %></td>
  </tr>
</table>

<div id="comments">
<strong >Comments :</strong>
  <table class="table">
    <% @game.comments.each do |comment| %>
        <tr><td>"<%= comment.text %>"<cite> by <%= comment.user.email %></cite></td></tr>
    <% end %>
  </table>
</div>  
  <!--  link_to "New comment", new_game_comment_path(@game, :format => :js), :remote => true, :id => "new_comment_link" %> -->
<% if can? :create, Comment %>  
  <%= render :file => "app/views/comments/new"%>
<% end %>


<% if @game.owned_by? current_user %>
	<%= link_to 'Edit', edit_game_path(@game) %> 
<% end %>
<%= link_to 'Back', games_path %> <br><br>
<%= render 'notify_friend' %>