config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :comments
    member do
      post :notify_friend
    end
  end
  resources :users do
    member do 
      post :sign_up_mail
    end
  end
  resources :tournaments do
    resources :matches
  end
  
  
 namespace :api do
  resources :games
 end

  
  resource :session
  match "/login" => "sessions#new", :as => "login", via: [:get, :post]
  match "/logout" => "sessions#destroy", :as => "logout", via: [:get, :post]
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

  root 'games#index'

  
  match "tournament/:id/register" => "tournaments#register", as: :tournament_register, via: [:get, :post]
  
  match "my_matches" => "matches#list", as: :my_matches, via: [:get, :post]
  match "all_match" => "matches#all", as: :all_match, via: [:get, :post] 
  match "ranking" => "tournaments#ranking", as: :ranking, via: [:get, :post] 
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Game</title>
  <link href="/assets/favicon.png" rel="shortcut icon"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- <%=javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Rails Game", root_path, :class =>"navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li> <!-- class="active"-->
            <li><%= link_to "Listing Games", games_path %> </li>
            <li><%= link_to "Listing Tournaments", tournaments_path %></li>
            <li><%= link_to "Listing Matches", all_match_path %></li>
            <li><%= link_to "Ranking", ranking_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
	    	<% unless current_user %>
	    		<li><%= link_to "Sign up", new_user_path %></li>
				<li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %><li/>
				<li><%= link_to "Sign in", login_path %> <li/>
			<% else %>
				<% if current_user.provider %>
					<li><%= link_to "Signed in as #{current_user.name} - #{current_user.id}", edit_user_path(current_user) %></li>
				<% else %>
					<li><%= link_to "Signed in as #{current_user.email} - #{current_user.auth_token}", edit_user_path(current_user) %></li>
				<% end %>
				<li><%= link_to 'Sign out', logout_path%> </li>
			<% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<div class="main">
	<div class="banner">
		<center><%= image_tag("banner.png", :alt =>"banner", :class => "img-banner")%></center>
	</div>
	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
	
	<div class="container">
	    <%= yield %>
	</div>
	<div class="footer">
		<center><%= image_tag("footer.png", :alt =>"banner", :class => "img-footer")%></center>
	</div>
</div>
</body>
</html>